blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://github.com/google/gvisor/blob/master/SECURITY.md
    about: Please report security vulnerabilities using the process described here.
