name: Action
on:
  pull_request:
    types: [labeled]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    if: "github.event.label.name == 'test'"
    steps:
      - name: Add commit comment
        run: |
          jq -nc '{"body": "trying action"}' | \
          curl -sL  -X POST -d @- \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "${{ github.event.pull_request.comments_url }}"
      - name: Bazel
        uses: google/gvisor@master
        with:
          target: "help"
