name: Action
on:
  pull_request:
    types: [labeled]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    if: "github.event.label.name == 'test'"
    steps:
      - name: Add commit comment
        run: |
          jq -nc '{"body": "trying action"}' | \
          curl -sL  -X POST -d @- \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "${{ github.event.pull_request.comments_url }}"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bazel
        uses: ./
        with:
          target: "help"
  test:
    runs-on: ${{ matrix.os }}
    name: Matrix
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        platform: [ptrace, kvm]
    steps:
      - name: Add commit comment
        run: |
          jq -nc '{"body": "using platform ${{matrix.platform}}"}' | \
          curl -sL  -X POST -d @- \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "${{ github.event.pull_request.comments_url }}"
