name: Test
on:
  issues:
    types: [labeled]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    if: "github.event.label.name == 'kokoro: run'"
    steps:
      - name: Add commit comment
        run: |
          jq -nc '{"body": "label detected, config from PR"}' | \
          curl -sL  -X POST -d @- \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "${{ github.event.issue.comments_url }}"
      - name: Delete label
        run: |
          curl -sL  -X DELETE \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "${{ github.event.issue.url }}/labels/kokoro:%20run"
